In [2]:
import pandas as pd

df = pd.read_csv("email.csv", sep=";")

In [3]:
df.head()

,Login email,Identifier,One-time password,Recovery code,First name,Last name,Department,Location
0,rachel@example.com,9012,12se74,rb9012,Rachel,Booker,Sales,Manchester
1,laura@example.com,2070,04ap67,lg2070,Laura,Grey,Depot,London
2,craig@example.com,4081,30no86,cj4081,Craig,Johnson,Depot,London
3,mary@example.com,9346,14ju73,mj9346,Mary,Jenkins,Engineering,Manchester
4,jamie@example.com,5079,09ja61,js5079,Jamie,Smith,Engineering,Manchester

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Login email        5 non-null      str
 1   Identifier         5 non-null      int64
 2   One-time password  5 non-null      str
 3   Recovery code      5 non-null      str
 4   First name         5 non-null      str
 5   Last name          5 non-null      str
 6   Department         5 non-null      str
 7   Location           5 non-null      str
dtypes: int64(1), str(7)
memory usage: 452.0 bytes

In [5]:
df.describe()

        Identifier
count     5.000000
mean   5917.600000
std    3170.552523
min    2070.000000
25%    4081.000000
50%    5079.000000
75%    9012.000000
max    9346.000000

In [6]:
df.shape

(5, 8)