#Estudo com Base de dados de Vendas da hashtag

In [56]:
import pandas as pd

vendas = pd.read_excel("Curso Básico Power BI 2025 - Aula 1 - Introdução ao Power BI/Base Vendas - 2022.xlsx")
produtos = pd.read_excel("Curso Básico Power BI 2025 - Aula 1 - Introdução ao Power BI/Cadastro Produto.xlsx")

In [57]:
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 371102 entries, 0 to 371101
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      371102 non-null  datetime64[us]
 1   Id Loja         371102 non-null  int64
 2   Id Produto      371102 non-null  int64
 3   Id Cliente      371102 non-null  int64
 4   Qtd. Vendida    371102 non-null  int64
 5   Qtd. Devolvida  371102 non-null  int64
 6   Preco Unitario  371102 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 19.8 MB

In [18]:
vendas.describe()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida
count,371102,371102.000000,371102.000000,371102.000000,371102.000000,371102.000000
mean,2022-07-01 12:34:23.251612,690.820413,1589.441997,9311.347409,1.000046,0.005629
min,2022-01-01 00:00:00,423.000000,1.000000,1.000000,1.000000,0.000000
25%,2022-04-02 00:00:00,559.000000,1676.000000,4629.000000,1.000000,0.000000
50%,2022-07-03 00:00:00,693.000000,1706.000000,9474.000000,1.000000,0.000000
75%,2022-09-28 00:00:00,823.000000,1768.000000,14101.750000,1.000000,0.000000
max,2022-12-31 00:00:00,952.000000,2512.000000,18484.000000,4.000000,1.000000
std,NaN,152.245359,476.687505,5383.712244,0.009711,0.074816

In [20]:
vendas.columns

Index(['Data Venda', 'Id Loja', 'Id Produto', 'Id Cliente', 'Qtd. Vendida',
       'Qtd. Devolvida', 'Preco Unitario'],
      dtype='str')

In [22]:
vendas.shape

(371102, 7)

In [17]:
vendas.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
0,2022-01-01,500,83,7604,1,0,99.99
1,2022-01-01,879,83,7605,2,0,99.99
2,2022-01-01,679,83,7606,1,0,99.99
3,2022-01-01,791,83,7607,1,0,99.99
4,2022-01-01,644,83,7608,4,0,99.99

In [ ]:
#Verificação da existência de campos nulos
vendas.isnull().sum()

Data Venda        0
Id Loja           0
Id Produto        0
Id Cliente        0
Qtd. Vendida      0
Qtd. Devolvida    0
Preco Unitario    0
dtype: int64

In [38]:
vendas[vendas.duplicated(keep=False)].sort_values("Id Loja")

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
370107,2022-12-31,452,344,1,1,0,366.00
370141,2022-12-31,452,344,1,1,0,366.00
370216,2022-12-31,465,378,1,1,0,758.00
370218,2022-12-31,465,378,1,1,0,758.00
370093,2022-12-31,521,414,1,1,0,758.00
370181,2022-12-31,521,414,1,1,0,758.00
370192,2022-12-31,739,414,1,1,0,758.00
370179,2022-12-31,739,414,1,1,0,758.00
370131,2022-12-31,860,392,1,1,0,382.95
370133,2022-12-31,860,392,1,1,0,382.95
370116,2022-12-31,929,347,1,1,0,586.00
370123,2022-12-31,929,347,1,1,0,586.00

In [40]:
vendas[vendas["Preco Unitario"].str.contains(',')]

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
4703,2022-01-05,482,1733,5463,1,0,"2278.,8"
4704,2022-01-05,606,1733,5464,1,0,"2278.,8"
4705,2022-01-05,809,1733,5465,1,0,"2278.,8"
4706,2022-01-05,942,1733,5466,1,0,"2278.,8"
4707,2022-01-05,605,1733,5467,1,0,"2278.,8"
...,...,...,...,...,...,...,...
368775,2022-12-30,745,1733,8316,1,0,"2278.,8"
368776,2022-12-30,823,1733,8317,1,0,"2278.,8"
368777,2022-12-30,638,1733,8318,1,0,"2278.,8"
368778,2022-12-30,595,1733,8319,1,0,"2278.,8"
368779,2022-12-30,482,1733,8320,1,0,"2278.,8"

In [42]:
vendas["Preco Unitario"].str.contains('.').sum()

np.int64(371102)

In [43]:
vendas["Preco Unitario"] = (
    vendas["Preco Unitario"]
        .str.replace("R$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
)

In [44]:
vendas["Preco Unitario"] = vendas["Preco Unitario"].astype(float)

In [45]:
vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 371102 entries, 0 to 371101
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      371102 non-null  datetime64[us]
 1   Id Loja         371102 non-null  int64
 2   Id Produto      371102 non-null  int64
 3   Id Cliente      371102 non-null  int64
 4   Qtd. Vendida    371102 non-null  int64
 5   Qtd. Devolvida  371102 non-null  int64
 6   Preco Unitario  371102 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5)
memory usage: 19.8 MB

In [46]:
vendas.describe()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
count,371102,371102.000000,371102.000000,371102.000000,371102.000000,371102.000000,371102.000000
mean,2022-07-01 12:34:23.251612,690.820413,1589.441997,9311.347409,1.000046,0.005629,180.198455
min,2022-01-01 00:00:00,423.000000,1.000000,1.000000,1.000000,0.000000,4.980000
25%,2022-04-02 00:00:00,559.000000,1676.000000,4629.000000,1.000000,0.000000,6.990000
50%,2022-07-03 00:00:00,693.000000,1706.000000,9474.000000,1.000000,0.000000,32.000000
75%,2022-09-28 00:00:00,823.000000,1768.000000,14101.750000,1.000000,0.000000,70.130000
max,2022-12-31 00:00:00,952.000000,2512.000000,18484.000000,4.000000,1.000000,3199.990000
std,NaN,152.245359,476.687505,5383.712244,0.009711,0.074816,480.766103

[423 424 425 426 430 431 432 433 434 435 436 437 438 439 440 441 442 443
 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461
 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 478 479 480
 481 482 483 485 486 487 488 490 491 492 493 494 495 496 497 498 499 500
 501 502 503 504 505 506 507 508 509 510 511 512 513 515 516 517 518 519
 520 521 522 523 524 525 527 528 529 530 531 532 533 534 535 536 537 538
 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556
 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574
 575 576 577 578 579 580 581 582 583 584 585 586 587 588 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 631 632 633 634 635 637 638 639 640 641 642 643 644 645 646 647 648 649
 650 651 652 653 654 655 656 657 658 659 660 661 662 664 665 666 667 668
 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686
 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704
 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722
 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740
 741 742 743 745 746 747 748 749 750 751 752 753 754 755 756 757 758 759
 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776 777
 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792 793 794 795
 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810 811 812 813
 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828 829 830 831
 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846 847 848 849
 850 851 852 853 854 855 856 857 858 859 860 861 862 863 864 865 866 867
 868 869 870 871 872 873 874 875 876 877 878 879 880 881 882 883 884 885
 886 887 888 889 890 891 892 893 894 895 896 897 898 899 900 901 902 903
 904 905 906 907 908 909 910 911 912 913 914 915 916 917 918 919 920 921
 922 923 924 925 926 927 928 929 930 931 932 933 934 935 936 937 938 939
 940 941 942 943 944 945 946 947 948 949 950 951 952]