# Tratamento das Planilhas de Cadastro

In [1]:
import pandas as pd
from src.limpeza import ajusta_nome, substitui_genero, limpar_preco

In [2]:
clientes = pd.read_excel("../raw/Cadastro Clientes.xlsx")
lojas = pd.read_excel("../raw/Cadastro Lojas.xlsx")
produtos = pd.read_excel("../raw/Cadastro Produto.xlsx")

---
## Clientes

In [3]:
clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 18484 entries, 0 to 18483
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id Cliente         18484 non-null  int64
 1   Nome Completo      18484 non-null  str
 2   Genero             18484 non-null  str
 3   Data de Nacimento  18484 non-null  datetime64[us]
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 577.8 KB

In [4]:
clientes.shape

(18484, 4)

In [5]:
clientes.isnull().sum()

Id Cliente           0
Nome Completo        0
Genero               0
Data de Nacimento    0
dtype: int64

In [6]:
clientes.head()

   Id Cliente Nome Completo Genero Data de Nacimento
0           1     P., Juana      F        1991-04-07
1           2  L., Apoliano      M        1990-05-13
2           3  G., Thatiane      F        1990-08-11
3           4      R., Gate      F        1993-02-13
4           5    N., Darcio      M        1993-08-07

In [7]:
clientes = ajusta_nome(clientes, "Nome Completo")

In [8]:
clientes["Nome Cliente"] = clientes["Nome Completo"].str.split(" ", expand=True).apply(lambda x: f"{x[0]}", axis=1)

In [9]:
clientes.head()

   Id Cliente Nome Completo Genero Data de Nacimento Nome Cliente
0           1      Juana P.      F        1991-04-07        Juana
1           2   Apoliano L.      M        1990-05-13     Apoliano
2           3   Thatiane G.      F        1990-08-11     Thatiane
3           4       Gate R.      F        1993-02-13         Gate
4           5     Darcio N.      M        1993-08-07       Darcio

In [10]:
clientes = substitui_genero(clientes, "Genero")
clientes.rename(columns={"Genero":"Gênero"}, inplace=True)

In [11]:
clientes.rename(columns={"Data de Nacimento":"Data de Nascimento"}, inplace=True)

In [12]:
clientes.head()

   Id Cliente Nome Completo     Gênero Data de Nascimento Nome Cliente
0           1      Juana P.   Feminino         1991-04-07        Juana
1           2   Apoliano L.  Masculino         1990-05-13     Apoliano
2           3   Thatiane G.   Feminino         1990-08-11     Thatiane
3           4       Gate R.   Feminino         1993-02-13         Gate
4           5     Darcio N.  Masculino         1993-08-07       Darcio

In [13]:
clientes.isnull().sum()

Id Cliente            0
Nome Completo         0
Gênero                0
Data de Nascimento    0
Nome Cliente          0
dtype: int64

In [14]:
clientes.duplicated().sum()

np.int64(0)

In [15]:
clientes.to_excel("../processed/clientes.xlsx", index=False)

---
## Lojas

In [16]:
lojas.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Cadastro Lojas - 2024  518 non-null    object
 1   Unnamed: 1             518 non-null    str
 2   Unnamed: 2             518 non-null    str
 3   Unnamed: 3             518 non-null    str
 4   Unnamed: 4             518 non-null    str
 5   Unnamed: 5             518 non-null    str
 6   Unnamed: 6             1 non-null      str
dtypes: object(1), str(6)
memory usage: 28.6+ KB

In [17]:
lojas.shape

(520, 7)

In [18]:
lojas.head()

,Cadastro Lojas - 2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Id Loja,Localidade,Cidade,Tipo Loja,Nome Gerente,Sobrenome Gerente,NaN
3,423,Inglaterra - Europa,Basingstoke Hants,Física,Beatriz,Lima,NaN
4,424,Estados Unidos - América do Norte,Bellevue,Física,Maria,Costa,NaN

In [19]:
lojas = lojas.drop(columns="Unnamed: 6")    #exclusão da coluna
lojas.columns = lojas.iloc[2]   #substituição do cabeçalho
lojas = lojas.iloc[3:].reset_index(drop=True)   #exclusão das linhas

In [20]:
lojas.head()

2,Id Loja,Localidade,Cidade,Tipo Loja,Nome Gerente,Sobrenome Gerente
0,423,Inglaterra - Europa,Basingstoke Hants,Física,Beatriz,Lima
1,424,Estados Unidos - América do Norte,Bellevue,Física,Maria,Costa
2,425,Austrália - Austrália,Bendigo,Física,João,Mendes
3,426,Inglaterra - Europa,Berks,Online,Sofia,Rocha
4,430,Estados Unidos - América do Norte,Beverly Hills,Física,Lucas,Gomes

In [21]:
lojas.isnull().sum()

2
Id Loja              0
Localidade           0
Cidade               0
Tipo Loja            0
Nome Gerente         0
Sobrenome Gerente    0
dtype: int64

In [22]:
lojas["Localidade"].unique()

<StringArray>
[              'Inglaterra - Europa', 'Estados Unidos - América do Norte',
             'Austrália - Austrália',                   'França - Europa',
                 'Alemanha - Europa',         'Canada - América do Norte',
              'Turcomenistão - Ásia',                  'Tailândia - Ásia',
                      'China - Ásia',                'Quirguistão - Ásia',
              'Coreia do Sul - Ásia',                      'Síria - Ásia',
                  'Paquistão - Ásia',                      'India - Ásia',
                      'Japão - Ásia',                  'Singapura - Ásia',
                     'Taiwan - Ásia',                        'Irã - Ásia',
                      'Butão - Ásia',                    'Armenia - Ásia',
                  'Holanda - Europa',                   'Grécia - Europa',
                    'Suíça - Europa',                  'Romênia - Europa',
                'Dinamarca - Europa',                  'Irlanda - Europa',
                   'Itália - Europa',                 'Portugal - Europa',
                'Eslovenia - Europa',                  'Espanha - Europa',
                   'Russia - Europa',                   'Suécia - Europa',
                    'Malta - Europa',                  'Polônia - Europa']
Length: 34, dtype: str

In [23]:
lojas["Cidade"].unique()[50:100:]

<StringArray>
[    'East Brisbane',           'Edmonds',         'Eilenburg',
     'Esher-Molesey',             'Essen',         'Frankfurt',
         'Gateshead',   'Gloucestershire',        'Gold Coast',
         'Grossmont',             'Haney',           'Hanover',
        'Hervey Bay',            'Hobart',    'Imperial Beach',
          'Issaquah',              'Kiel',            'Kirkby',
         'Lancaster',           'Langley',           'Lebanon',
             'Leeds',       'Lemon Grove',          'Les Ulis',
         'Lieusaint',     'Lincoln Acres',            'London',
          'Lynnwood',        'Marysville',        'Matraville',
            'Melton',         'Metchosin',     'Milsons Point',
  'Mühlheim am Main',           'Munster',     'National City',
       'Neunkirchen',         'Newcastle',        'North Ryde',
           'Oakland', 'Offenbach am Main',           'Olympia',
       'Oregon City',              'Orly',            'Oxford',
         'Palo Alto',            'Pantin',             'Paris',
  'Paris La Defense',             'Perth']
Length: 50, dtype: str

In [24]:
lojas.describe()

2,Id Loja,Localidade,Cidade,Tipo Loja,Nome Gerente,Sobrenome Gerente
count,517,517,517,517,517,517
unique,517,34,511,2,20,20
top,423,Estados Unidos - América do Norte,Saint Ouen,Física,Ana,Martins
freq,1,282,3,464,39,34

In [25]:
lojas.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id Loja            517 non-null    object
 1   Localidade         517 non-null    str
 2   Cidade             517 non-null    str
 3   Tipo Loja          517 non-null    str
 4   Nome Gerente       517 non-null    str
 5   Sobrenome Gerente  517 non-null    str
dtypes: object(1), str(5)
memory usage: 24.4+ KB

In [26]:
lojas.shape

(517, 6)

In [27]:
lojas.duplicated().sum()

np.int64(0)

In [39]:
lojas["Id Loja"] = lojas["Id Loja"].astype(int)

In [40]:
lojas.info()

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id Loja            517 non-null    int64
 1   Localidade         517 non-null    str
 2   Cidade             517 non-null    str
 3   Tipo Loja          517 non-null    str
 4   Nome Gerente       517 non-null    str
 5   Sobrenome Gerente  517 non-null    str
dtypes: int64(1), str(5)
memory usage: 24.4 KB

In [41]:
lojas.to_excel("../processed/lojas.xlsx", index=False)

---
## Produtos

In [29]:
produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id Produto    2517 non-null   int64
 1   Nome Produto  2517 non-null   str
 2   Categoria     2517 non-null   str
 3   Marca         2517 non-null   str
 4   Preço Unit.   2517 non-null   str
 5   Custo Unit.   2517 non-null   float64
dtypes: float64(1), int64(1), str(4)
memory usage: 118.1 KB

In [30]:
produtos.head()

,Id Produto,Nome Produto,Categoria,Marca,Preço Unit.,Custo Unit.
0,1037,A. Datum Advanced Digital Camera M300 Azure,Cameras and camcorders,A. Datum,188.50,86.68
1,953,A. Datum Advanced Digital Camera M300 Black,Cameras and camcorders,A. Datum,188.50,86.68
2,1023,A. Datum Advanced Digital Camera M300 Green,Cameras and camcorders,A. Datum,188.50,86.68
3,967,A. Datum Advanced Digital Camera M300 Grey,Cameras and camcorders,A. Datum,188.50,86.68
4,1009,A. Datum Advanced Digital Camera M300 Orange,Cameras and camcorders,A. Datum,188.50,86.68

In [31]:
produtos.isnull().sum()

Id Produto      0
Nome Produto    0
Categoria       0
Marca           0
Preço Unit.     0
Custo Unit.     0
dtype: int64

In [32]:
produtos.duplicated().sum()

np.int64(0)

In [33]:
produtos = limpar_preco(produtos, "Preço Unit.")

In [34]:
produtos.describe()

        Id Produto  Preço Unit.  Custo Unit.
count  2517.000000   2517.00000  2517.000000
mean   1259.000000    357.72644   147.655562
std     726.739637    495.49303   184.373683
min       1.000000      0.95000     0.480000
25%     630.000000     69.00000    32.250000
50%    1259.000000    199.99000    86.670000
75%    1888.000000    410.00000   183.950000
max    2517.000000   3199.99000  1060.220000

In [35]:
produtos.rename(columns={"Preço Unit.":"Preço Unitário"},inplace=True)
produtos.rename(columns={"Custo Unit.":"Custo Unitário"},inplace=True)

In [36]:
produtos.head()

,Id Produto,Nome Produto,Categoria,Marca,Preço Unitário,Custo Unitário
0,1037,A. Datum Advanced Digital Camera M300 Azure,Cameras and camcorders,A. Datum,188.5,86.68
1,953,A. Datum Advanced Digital Camera M300 Black,Cameras and camcorders,A. Datum,188.5,86.68
2,1023,A. Datum Advanced Digital Camera M300 Green,Cameras and camcorders,A. Datum,188.5,86.68
3,967,A. Datum Advanced Digital Camera M300 Grey,Cameras and camcorders,A. Datum,188.5,86.68
4,1009,A. Datum Advanced Digital Camera M300 Orange,Cameras and camcorders,A. Datum,188.5,86.68

In [37]:
produtos.to_excel("../processed/produtos.xlsx", index=False)